### ISSUE TITLE
persistence column order not working

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#3090]
**Describe the bug**
The column-persistence doesn't save the order of the columns after refresh

**Tabulator Info**
- 4.9.1

**Working Example**
[https://jsfiddle.net/ktxe8zfa/](https://jsfiddle.net/ktxe8zfa/)

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to [https://jsfiddle.net/ktxe8zfa/](https://jsfiddle.net/ktxe8zfa/)
2. rearrange the columns with the mouse
3. Refresh
4. Columns are in the default position

**Expected behavior**
I have expected it to work like in 4.8.X, that the columns are still rearranged after the refresh

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53866907/100103579-5eae7c00-2e65-11eb-8867-a0b648edff70.png)
default

![grafik](https://user-images.githubusercontent.com/53866907/100103647-74bc3c80-2e65-11eb-81e6-4f9b76dbe54e.png)
rearranged

after refresh it is default again

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 78.5.0esr (64-Bit)

Thanks you Oli

**Comment by empatlima530** [comment]
Yes, I have to exactly issue here as well.

**Comment by dannykln** [comment]
I'm noticed that too, its fine in 4.8.X, however in 4.9.1 columns are will rearrange back to default after refresh

**Comment by slidertom** [comment]
Yes, I have same issue.

**Comment by slidertom** [comment]
manual calls:
// save:
const data= table.getColumnLayout();
localStorage.setItem(id + "-" + type, JSON.stringify(data));

and restore:
const data = localStorage.getItem(id + "-" + type);
columnLayout = data ? JSON.parse(data) : null;
if (columnLayout) {
table.setColumnLayout(columnLayout);
}

works correctly.

**Comment by olifolkerd** [comment]
Hey All,

I have just pushed a fix for this to mater and will include it in this evenings patch release.

Cheers

Oli :)

**Comment by RawatAlMakan** [comment]
persistence column resizing and rearranging does not work in 5.2.7

**Comment by ArusikGrigorian** [comment]
Hey!!! Persistence for sorting and filtering is not working and rowClick is throwing an error [component.getComponent is not a function...] in react functional component. Is there any way to fix them?

Environment : "react": "^18.1.0", "react-tabulator": "^0.18.1".

**Comment by olifolkerd** [comment]
Hey @ArusikGrigorian 

This issue was closed years ago, any problems you are having are unrelated to this.

If you have an issue with react-tabulator please raise it on that repo first, this is only for the core tabulator-tables library.

If you think you have found a bug with the latest version of the core library then you should raise a new bug report including all the required details and an example js fiddle.

Cheers

Oli

**Comment by ArusikGrigorian** [comment]
oh, sorry and thank you!
