### ISSUE TITLE
rowSelection formatter doesn't work with bottomCalc in 4.8

### ISSUE THREAD

**Issue by MChr1Ss** [olifolkerd/tabulator#2982]
Hi Oli,
thank you for the tabulator, it's a very good tool :-)
Thanks for your support.

**Describe the bug**
If you use the bottomCalc an the formatter "rowSelection" together it throws the error
`TypeError: row.isSelected is not a function `
in 
`tabulator.js:19160:29`
![error_tab](https://user-images.githubusercontent.com/53866907/92745308-8885f580-f382-11ea-9c70-2cf90a45b1a0.jpg)

**Tabulator Info**
- 4.8 (it worked in 4.7)

**Working Example**
https://jsfiddle.net/ag8v6f0m/

**To Reproduce**
Run the JSFiddle. Then it throws an error.
If you delete the first or second column it will work.

**Desktop**
 - Browser FireFox
 - Version 68.12.0esr

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

Thanks for letting me know,

This is because of the new CalcComponent type that was introduced in the last update, it lacks the isSelected function as calc rows can be selected.

I will include a patch to fix this in tomorrows update.

Cheers

Oli :)

**Comment by olifolkerd** [comment]
Hey @MChr1Ss 

I have just pushed an update to the master branch to fix the ***rowSelection*** formatter so that it doesn't try to add a tickbox to calc rows.

Cheers

Oli :)

**Comment by MChr1Ss** [comment]
Thank you Oli  :)

It fixed one of the Problem, but there is another one:

Here in 4.8.1: https://jsfiddle.net/yeapd01t/
Here in 4.7.0: https://jsfiddle.net/x7u0g2kp/

The error is:  cell.getValue(...) is undefined

I think it is because, the cell-row type is "calc".

Do you want me to open a new Issue?

**Comment by olifolkerd** [comment]
Yes please
