### ISSUE TITLE
Cannot call 'cell.getData()' in tooltip formatter function

### ISSUE THREAD

**Issue by bornova** [olifolkerd/tabulator#3514]
Wanted to report this after coming accross a question on Stack Overflow (https://stackoverflow.com/questions/70365805/is-there-a-way-to-return-cell-data-as-a-tooltip-in-tabulator-v5-0-7)

**Describe the bug**
Calling `cell.getData()` in tooltip formatter function throws error: `Uncaught TypeError: cell.getData is not a function`

**Tabulator Info**
v5.0.8

**Working Example**
Working in v4.9.3: https://codepen.io/izmirli/pen/wvrdQoP
Not working in v5.0.8: https://codepen.io/izmirli/pen/qBPPawr

**Expected behavior**
Should be able to get row data by calling `cell.getData()`?

**Comment by olifolkerd** [comment]
Hey @bornova 

There was an issue where it was defaulting to the `tooltip` if the `headerTooltip` option was not set. I have pushed a fix for this to the master branch and will include it in the next patch release.

in the mean time if you set the `headerTooltip` option in the column defintion to an empty string this should stop the exception from being thrown.

Cheers

Oli :)
