### ISSUE TITLE
Beta 3.0 Feedback (24/05/2017)

### ISSUE THREAD

**Issue by Paraplegix** [olifolkerd/tabulator#328]
So i'm gonna take a look on switching from tabulator 2.12 to 3.0 and report back all the things i had to do or the problems I encountered, for people who wish to know what might cause problem and what to lock at immediately. 

I simply downloaded the 3.0 package from github and replaced boths .js and .css (i'm using the full version not the minified)

[Changes] are things i had to change for it to work and [Bugs] will be the things i couldn't get to work with Tabulator 3.0 or that are behaving in a funky way

- [_Change_] "sort" function is becoming "setSort", ~~seems to function the same way as before~~.
  :warning: almost missed but its no anymore `{field : "demandeid", dir : "asc" }` but `{column:"age", dir:"asc"}` ! field has been changed to column. If you use field there will be a warning saying sort field does not exist. 
  Also `initialSort`is perfect for what i had to do !
- [**Bug**] `("redraw",true)` does not seem to work, I have a "hidden" tabulator div, when it have to appear I set a timeout for the `("redraw",true)` call but it only refresh the rows and not the column header, I've also tryed to triger the sorting manualy from developper console  => see problem #226 
- [_Change_] "onClick" become "cellClick", arguments are also changed to embrace the components ! It was a "delete row" type of button in the cell, so i was simply getting the id of the data and (with intermediary step) asked tabulator to remove the row based on this id (the "index" column). from `data.id` I have to go to `cell.getRow().getData().id` or `cell.getRow().getIndex()`... now I'm just thinking about all the thing's I'll have to change :sob:, regular expression will be the way to go !
- [**Bug**] self.element.appendClassis not a function TypeError  at [`self.element.appendClass(def.cssClass);`](https://github.com/olifolkerd/tabulator/blob/3.0/dist/js/tabulator.js#L1035). Its preventing table creation :sob:. **cssClass** of column is not supported ! remove it from your colum definition !
- [**Bug**] When you call `addColumn` or `deleteColumn` , tabulator fail at line 611 because `.redraw() is not a function` This completly mess up my dynamic column thingy :sob: 
- [_Change_] groupHeader works the same way out of the box, but the style is changed
- [**Bug**] Frozen Columns kinda buggy !!! 
  - If put on the firt column : Work well
  - If put on column inside of a group : Nothing happen :+1: 
  - If put on any column other than the first : the column is frozen to the right too ! But the cells are frozen with the column too.
  - If put on head of a group of colum at first position : The whole group get frozen to the... Right ! :rofl: But the cell in the rows are not frozen with the headers :disappointed: 
-  [_Change_] formatter changes ! argument changed to accord with the component thingy ! Nothing too hard.
- [_Change_] Group header now collapse en expand where you click anywhere on it instead of only the little arrow, might be cool to be able to deactivate that. I was adding some controle inputs into the headers. Now the group move everytime !
- [_Change_] `sortable `column parameter is now `headerSort` (used to "hide" the sorting arrow and prevent column sorting)

Well here is a _little unordered_ list of the things I immediately noticed.
Other addition like extensition seems like they allow a lot of new things.. Good work :exclamation:

Also maybe i've noticed a typo into the tabulator help looking at the "Advanced Component" section : 
```
Get Index
The **getInde** function returns the index value for the row.
var rowIndex = row.**getInde();**
```
And another in the frozen column section : 
`  {title:"Height", field:"height"}, //frozen column on right of table`
It is missing the `frozen:true` parameter 

Another in sorting data extension:
` {field:"start", title:"Start Time", mutator:"datetime"},`
Where `mutator` should be `sorter` I think
I'm gonna take a break now :coffee:

**Comment by olifolkerd** [comment]
Thanks for the detailed feedback, that is great!

Could you give me a bit more information on your "self.element.appendClass" bug, im not sure i understand where you are trying to do this?

I have just fixed the **addColumn*** ***deleteColumn*** redraw bug so you should be all good there.

I will have a detailed look into the frozen columns issues, as a rule it isnt supposed to work with grouped columns, but it should reject that altogether with a helpful message rather than corrupting the display so i will get that in this weekend.

with the group header collapse, i agree with you on that, i will restrict it back to the arrow this weekend.

I will update the documentation today and fix those issue.

Thanks for all your hard work there, I really appreciate the effort the Tabulator community is putting in to make this beta better!

Keep up the awesome job!

**Comment by Paraplegix** [comment]
Concerning the the "self.element.appendClass" bug. It happened when i was using the cssClass option for the [column definition](http://olifolkerd.github.io/tabulator/docs/3.0/#define-column-headers).

In my case i needed to have one full column in blue background for easier "visualisation" in the middle of others. so i was using somthing like `cssClass : "blueBackgroundClass` inside my code, but when i was using this, Javascipt or jquery threw error : "self.element.appendClass is not a function TypeError at ".

**Comment by alainpannetier** [comment]
>>> Concerning the the "self.element.appendClass"
You can edit tabulator at that line and change for 'addClass' and that will do it.

**Comment by olifolkerd** [comment]
Hey,

I have just committed some patches to fix those issues.

- The  ***cssClass*** property should now work
- groups should now only collapse when the arrow is clicked, 
- frozen columns on groups should no longer work and will display a sensible warning in the console

Let me know if you have any other feedback.

Cheers

Oli
