### ISSUE TITLE
Custom headerFilter not loaded in 3.x

### ISSUE THREAD

**Issue by leonardorame** [olifolkerd/tabulator#411]
Hi, I was using this custom headerFilter in 2.x and it worked perfectly, now I upgraded to 3.x (from trunk) and the header filter is not displayed anymore:

```javascript
// Global variable "ajaxFilter" to be used by Tabulator's 
// to filter server-side.

ajaxFilter= function (cell, value, data){

  //create and style input
  var input = $("<input type='text' class='ajax-filter'/>");
  input.css({
    "padding-left":"2px",
    "padding-right":"2px",
    "font-weight": "normal",
    "width":"100%",
    "box-sizing":"border-box",
    "border": "1px solid gray",
    "border-radius": "1px"
  })

  //wait till element is added to dom before altering event bindings
  setTimeout(function(){
    //block existing filter event bindings
    input.off("keyup change blur keydown");

    //submit new value on change
    input.on("change", function(e){
      var tabulator = $('#' + cell.closest(".tabulator")[0].id);
      var params = tabulator.tabulator("option").ajaxParams;
      // generate parameter's list
      $(tabulator.selector + " .tabulator-header-filter .ajax-filter").each(function(){
        var element = $(this);
        var key = element.closest(".tabulator-col").data("field");

        if(element.val() !== ""){
          params[key] = element.val();
        } else {
          delete params[key];
        };
      });
      // get the original ajaxURL
      var ajaxURL = tabulator.tabulator("option").ajaxURL;
      // perform the ajax call
      tabulator.tabulator("setData", ajaxURL, params);
    });
  }, 300);

  return input;
}

```
This is the configuration:
```javascript
      $('#my-table').tabulator({
        headerFilterPlaceholder: "",
        selectable: 1,
        pagination: "remote",
        ajaxURL: "/cgi-bin/imtranscript.bf/reports",
        height: "311px",
        columns:[
          {title:"Audio", field: "tieneaudio", sortable: true, sorter:"string", width: 100, editable: false},
          {title:"Informe", field: "tieneinforme", sortable: true, sorter:"string", width: 100, editable: false},
          {title:"Id", field: "idturno", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Estado", field: "nombreestado", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Ingreso", field: "turnosistemaexterno", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Fecha", field: "fecha", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Hora", field: "hora", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Modalidad", field: "modalidad", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Región", field: "region", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Paciente", field: "paciente", sortable: true, sorter:"string", width: 150, editable: false, headerFilter: ajaxFilter},
          {title:"Documento", field: "nrodocumento", sortable: true, sorter:"string", width: 100, editable: false, headerFilter: ajaxFilter},
          {title:"Descripción", field: "especialidad", sortable: true, sorter:"string", width: 200, editable: false, headerFilter: ajaxFilter},
          {title:"Institución", field: "institucion", sortable: true, sorter:"string", width: 150, editable: false, headerFilter: ajaxFilter}
        ]
      });
```
BTW, I'm also getting: `TypeError: t.widget(...) is not a function   tabulator.min.js:4:23182` since upgrading to 3.x, but Tabulator is displayed and works ok (with no headerFilter).

Here's what I'm getting:

![imagen](https://user-images.githubusercontent.com/1405017/27605150-22cadd12-5b52-11e7-874e-0e3ff2752dbc.png)

**Comment by olifolkerd** [comment]
Hey,

I have a few pointers to help you with the migration to 3.1.

You don't need to set the ***editable*** property in the column definition to false, you can just leave it out, this is its default value.

You no longer need to set the ***sortable*** property any more this no longer exists, all columns are sortable. if you want to disable the header sorting on click you can set the ***headerSort*** property to false for that column

On most of your columns you wont need to include use the ***sorter*** property either, in 3.xx tabulator can automatically  work out how to sort the data in each column based on its contents, you should only set the sorter if you want to force a certain type of sort.

The issue you are having with your header filter is because from 3.0 onward there are a new set of arguments to the custom editor  functions (and thus the custom header formatter functions). See the [Editing & Manipulation Data Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#manipulating-data) for details on how this now works

Five new arguments are passed:
- **cell** - the cell component that can be used to retrieve the value for the element and much more (see [Cell Component Docs](http://olifolkerd.github.io/tabulator/docs/3.1/#component-cell))
- **onRendered** - a callback that is triggered when the editor has been renders (replaces the timeout)
- **success** - a function to pass the updated value to the system for processing
- **cancel** - a function to all if the users actions indicate they wish to abort the edit
- **editorParams** - the editorParams object from the column definition if defined

You are also trying to access table and cell data through the DOM elements. this is no longer possible in version 3.0 as it uses virtual rendering the element only exist while they are visible in the table, when they are scrolled out of view they are destroyed, the jQuery data function is no longer used. All data access is now done through the component objects passed into the callback, which provides a much cleaner way to access the data (see [Component Object Documentation](http://olifolkerd.github.io/tabulator/docs/3.1/#components)).

You can now use the ***getFilter*** function to retrieve all filters on the table which may be a more suitable way to get all of the filters currently in use.

```js
var filters = $("#example-table").tabulator("getFilter");
```

I would recommend having a read through the filtering, editing and component documentation as there have been a load of new features added which make things much simpler and give more functionality in 3.xx

And just so you know, passing all filter data back in the ajax request automatically is on the roadmap for next months 3.2 release so you wont even need your custom filter at that point, it should all just work for you then.

Let me know if you need any further help

Cheers

Oli

**Comment by leonardorame** [comment]
Thanks for this extensive response, well done.

After reading it I've made the required changes to my "ajaxFilter" but it still didn't show in my grid, then I dived into the code and found this in line 6941:

```editor = column.definition.editor;```

Then after looking at my column definition I've found there wasn't an `editor` field, so I replaced that with:

```editor = column.definition.headerFilter;```

And it worked!.

So, is this a bug?.

**Comment by olifolkerd** [comment]
Hey,

Good spot, that was a bug, i have just pushed an update to the master branch, it will be included in this weekends hotfix release.

Cheers

Oli

**Comment by leonardorame** [comment]
Hi Oli, after a couple of months I'm trying to adapt my grids to Tabulator 3.2.x, so far the only issue I'm facing is my custom editor is shown, but the event `editor.on("change")` isn't called.

Here's my editor:

```  ajaxFilter = function(cell, onRendered, success, cancel, editorParams){
      //create and style input
      var editor = $("<input type='text'/>");
      editor.css({
        "padding-left":"2px",
        "padding-right":"2px",
        "font-weight": "normal",
        "width":"100%",
        "box-sizing":"border-box",
        "border": "1px solid gray",
        "border-radius": "1px"
      });
      
      editor.val(cell.getValue());
    
      onRendered(function() {
        editor.focus();
      });

      editor.on("change blur", function(e) {
        console.log('change');
        success(editor[0].val());
      });

      return editor;
  };
```

Any hint?.

**Comment by olifolkerd** [comment]
looking at that you want to change:
```js
success(editor[0].val());
```

to:
```js
success(editor.val());
```

hope that helps,

Cheers

Oli

**Comment by leonardorame** [comment]
Thanks, but the console.log before that isnt reached also.

**Comment by olifolkerd** [comment]
what action are you performing that you are expecting the change event to be fired for?

**Comment by leonardorame** [comment]
Typing text.

**Comment by olifolkerd** [comment]
could you post a copy of your entire table constructor?

Cheers

**Comment by leonardorame** [comment]
Yes:
 table.tabulator({
      height: '320px',
      selectable: 1,
      pagination: "remote",
      headerFilterPlaceholder: "",
      ajaxFiltering: true,
      ajaxURL: "/cgi-bin/smartmonitor.bf/ranking_envios",
      ajaxRequesting: function(url, params) { 
        var filters = table.tabulator("getFilter");
        console.log(filters);
      },
      columns:[
        {title:"#", field: "position", headerFilter: ajaxFilter, sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Ingreso", field: "ingreso",headerFilter: ajaxFilter, sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Creado", field: "creado", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 150, editable: false},
        {title:"Fecha", field: "fecha", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Hora", field: "hora", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Paciente", field: "paciente", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 250, editable: false},
        {title:"Informe", field: "informeenviado", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Imágenes", field: "imageneseviadas", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Reintentos", field: "reintentos", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Borrado", field: "borrado", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"Recuperando", field: "recuperando", headerFilter: ajaxFilter,sortable: true, sorter:"string", width: 100, editable: false},
        {title:"RAW", field: "raw", sortable: true,headerFilter: ajaxFilter, sorter:"string", width: 100, editable: false}
      ]
    });

**Comment by leonardorame** [comment]
Sorry, looks horrible. I'm on the phone.

**Comment by olifolkerd** [comment]
on headerFilters the ***change*** event for input element is overridden by the filter system as it gets handled differently, so it is being called, it is justthe binding in the editor has been replaced with the one internally in the header filter system. it should function correctly it just wont call the function in tour editor

**Comment by leonardorame** [comment]
Sorry, I don't understand. How can I get the values I typed into the header filter to arrange them onto an ajax call to my server?.

**Comment by olifolkerd** [comment]
ahhh,

I see where the confusion is coming from.

at the moment only the first programmatic filter is automatically added to the request to the server when ***ajaxFiltering*** is enabled. header filters are not passed in this mode

The 3.3 release next month will include improved ajax filtering including header filters.

Cheers

Oli

**Comment by leonardorame** [comment]
I know that, but, isn't there a way to implement it by myself before that?

**Comment by olifolkerd** [comment]
You could bind to the keyup event instead that would let you check when a user has typed in the editor, you could then have an object external to tabulator that stores the value of the editor against the column filed as the key.

You could then trigger an ajax call passing that filters object in as a parameter, and then pass the returned data to tabulator with the ***setData*** function.

Does that help?

Cheers

Oli

**Comment by leonardorame** [comment]
Yes, I'll try that.

**Comment by leonardorame** [comment]
Hi again Oli, I'm trying to make this work.

I've created this extension:

```javascript
Tabulator.extendExtension("edit", "editors", {
        ajaxEditor: function(cell, onRendered, success, cancel, editorParams){
          //create and style input
          var editor = $("<input type='text'/>");
          editor.css({
            "padding-left": "2px",
            "padding-right": "2px",
            "font-weight": "normal",
            "width": "100%",
            "box-sizing": "border-box",
            "border": "1px solid gray",
            "border-radius": "1px"
          });
          editor.val(cell.getValue());
          onRendered(function () {
            editor.focus();
          });
          editor.on("keyup", function (e) {
            console.log(editorParams);
            console.log(cell);
          });
          return editor;
        },
    });```

And defined this colums array:

```javascript
{ title: "#", field: "position", headerFilter: "ajaxEditor", headerFilterParams: {"field": "position"}, ...
```
As you can see, I'm forced to include the `headerFilterParams` property because from the editor I cannot use `cell.getField()`. I thing that method only works for *cell* editors, but not for *headerFilters*. Can you add that method for headerFilter editors?.

**Comment by olifolkerd** [comment]
Hey @leonardorame,

Great idea, it was a quick fix so i have just pushed an update for this to the master branch, it will be included in the next official release.

Could i ask that you raise feature requests in a new issue as it make it easier for me to track them when it comes to building the next release.

Cheers

Oli

**Comment by leonardorame** [comment]
Thanks, I'm creating a new issue right now.
