### ISSUE TITLE
Change in filter behavior with _row

### ISSUE THREAD

**Issue by aklaver** [olifolkerd/tabulator#3127]
**Describe the bug**
Have been testing version 4.9.1 versus 4.8.4. When using dataFiltered callback using _row.element.click it fails with "._row.element.click is not a function". This does work when you do it outside dataFiltered and it works in 4.8.4.

**Tabulator Info**
4.9.1

**Working Example**
4.8.4 example:
https://jsfiddle.net/aklaver/6cL1a89u/

4.9.1 example:
https://jsfiddle.net/aklaver/w9o15sek/

**To Reproduce**
In  both cases click Filter and Click Row.
The 4.9.1 version is setup to work by using getElements(). To create failure comment out those lines and uncomment _row.element lines.

**Expected behavior**
That the behavior would be the same in both versions.

**Desktop (please complete the following information):**
 OpenSuSE 15.1
Firefox 83

**Comment by olifolkerd** [comment]
Hey @aklaver 

You should never be using any properties or functions on an underscore property. it is standard JavaScript convention that these are to be considered private.

Which is whey they are un-docmented and subject to change without notice. making any use of these may result in unintended functionality of the table.

The various [Component Objects](http://tabulator.info/docs/4.9/components) provide full access to any part of the table necessary.

Cheers

Oli :)
