### ISSUE TITLE
select row after filtering

### ISSUE THREAD

**Issue by cschnelting** [olifolkerd/tabulator#684]
Hi Oli,

I would like to select the first Row after dataFiltered Event. It works fine in Tabulator v3.2, but after updating to Tabulator v3.3 its not working. 

My EventHandler: 
`dataFiltered:function(filters, rows){
     //filters - array of filters currently applied
     //rows - array of row components that pass the filters
     if(rows.length > 0) {
         rows[0].select();
     }
}`

And I get the following Error:

> Uncaught TypeError: this.row.selectRows is not a function
    at RowComponent.select (tabulator.js:3506)
    at Object.dataFiltered (avisBearbeitung.js:184)
    at Filter.filter (tabulator.js:9356)
    at RowManager.refreshActiveData (tabulator.js:2737)
    at RowManager.setData (tabulator.js:2256)
    at Page._parseRemoteData (tabulator.js:12890)
    at tabulator.js:12876
    at Object.<anonymous> (tabulator.js:7023)
    at fire (jquery.js:3317)
    at Object.fireWith [as resolveWith] (jquery.js:3447)
RowComponent.select @ tabulator.js:3506
dataFiltered @ avisBearbeitung.js:184
Filter.filter @ tabulator.js:9356
RowManager.refreshActiveData @ tabulator.js:2737
RowManager.setData @ tabulator.js:2256
Page._parseRemoteData @ tabulator.js:12890
(anonymous) @ tabulator.js:12876
(anonymous) @ tabulator.js:7023
fire @ jquery.js:3317
fireWith @ jquery.js:3447
done @ jquery.js:9272
(anonymous) @ jquery.js:9514
XMLHttpRequest.send (async)
send @ jquery.js:9566
ajax @ jquery.js:9173
Ajax.sendRequest @ tabulator.js:7014
Page._getRemotePageAuto @ tabulator.js:12874
Page._getRemotePage @ tabulator.js:12800
Page.trigger @ tabulator.js:12780
Page.setPage @ tabulator.js:12584
_loadInitialData @ tabulator.js:5192
(anonymous) @ jquery-ui.js:144
_create @ tabulator.js:5071
(anonymous) @ jquery-ui.js:144
_createWidget @ jquery-ui.js:341
$.(anonymous function).(anonymous function) @ jquery-ui.js:99
(anonymous) @ jquery-ui.js:281
each @ jquery.js:362
each @ jquery.js:157
$.fn.(anonymous function) @ jquery-ui.js:273
initGrid @ avisBearbeitung.js:132
init @ avisBearbeitung.js:22
(anonymous) @ avisBearbeitung.js:18
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930

Is there a Bug in Tabulator v3.3?

Thanks!

**Comment by Krigen** [comment]
Did you look at: http://tabulator.info/docs/3.3#selectable?

**Comment by cschnelting** [comment]
yes, i have option 

> selectable:1,

 
set

**Comment by olifolkerd** [comment]
could you post a copy of your tabulator constructor and the filter function you are using so i can test against it.

Cheers

Oli

**Comment by cschnelting** [comment]
I have the same Error in an other Tabulator-Grid where I use the cellDblClick-Event as following:

`function cellDblClick(e, cell) {
    cell.getRow().select();
}`

I get the Error:

> Uncaught TypeError: this.row.selectRows is not a function
    at RowComponent.select (tabulator.js:3509)

I'm using tabulator v3.3.1

**Comment by olifolkerd** [comment]
i will look at fixing this in next weeks bug fix release

**Comment by ParadauxDev** [comment]
Hey I really need selection to be fixed for my demo tomorrow if at all possible, thanks

**Comment by olifolkerd** [comment]
Hey, i have just pushed a fix for this to the mater branch, it will be included in this evenings update
