### ISSUE TITLE
row.getPosition works on topCalc  with 4.7.2 but not 4.8.4

### ISSUE THREAD

**Issue by sydesb** [olifolkerd/tabulator#3069]
**Describe the bug**
row.getPosition  -> works well with tabulator 4.7.2 but not with tabulator 4.8.4 in Chrome and Firefox :  **row.getPosition is not a function**
The context : 

```
new Tabulator("#tablecomp", {
       cellClick:function(e, cell){
	        	addclipboard(e,cell);
		     }
...........}

function addclipboard(e,cell)
{	myrow=cell.getRow();
        //Is it topCalc ? :
	if (myrow.getPosition(true)==-1){   // Here : row.getPosition is not a function
.......}
```

**Tabulator Info**
- 4.7.2 works but not 4.8.4

**Working Example**
4.7.2 -> https://codepen.io/sylv20/pen/jOreeYb       Works well
4.8.4-> https://codepen.io/sylv20/pen/RwReBzG      Doesn't work with the same code

**To Reproduce**
A step by step guide to recreate the issue in Codepen:
1. Click on a clipboard icon  -> alert ok with 4.7.2 but not with 4.8.4

**Desktop (please complete the following information):**
 - Windows 10
-Firefox and Chrome last version

**Comment by sydesb** [comment]
I don't know if it's the good solution but it works if we test the existence of  getPosition : 
`
 if (typeof myrow.getPosition !== "undefined") if (myrow.getPosition(true)==-1){ 

`

**Comment by olifolkerd** [comment]
This is correct. The calc rows have no position in the table.

In 4.8 the new calculation component was added for calculation rows instead of them using the standard row components

**Comment by sydesb** [comment]
ok, thank you and thank you very much for Tabulator !!!
